# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83400308d1b58297f78a16ba71d70b4f2985c1c65516d3e05ed79897a9107b918f60fe2cfa64c30aa327682f662eb005d2bb728a93af27a5f879ca4553c1f20f

test:
  secret_key_base: 9ca059099cf434cdabbab6244722be6512c273353a09c278c1540996e9ffbb500be74c2aa9569bb0cca008520ad81907e5fb4382fa024a2dae546c7c48d3ec9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
